name: ost
channels:
  - conda-forge
dependencies:
  - python=3.9.13
  - rdkit=2022.09.4
  - parmed=3.4.3
  - openbabel=3.1.1
  - openmm=8.0.0
  - openff-forcefields=2023.04.1
  - openff-toolkit=0.12.1
  - openff-models=0.0.4 
  - openff-units=0.2.0
  - openff-utilities=0.1.8
  - ambertools=22.4
  - toml=0.10.2
  - xmltodict=0.13.0
  - pyxtal=0.5.5
  - pymatgen=2022.9.8
  - pip:
    - git+https://github.com/shinnosukehattori/openff-interchange@main
  #Dev tools at github commit
  - black
  - flake8
  - isort
  - pre-commit
  - pytest
  - pytest-cov
  - pdoc3
